export const USER_CREATE_SOLICITUD  = 'USER_CREATE_SOLICITUD';
export const USER_CREATE_EJECUCION = 'USER_CREATE_EJECUCION';
export const USER_CREATE_RESPONSE = 'USER_CREATE_RESPONSE'; 

export const USER_GET_SOLICITUD  = 'USER_GET_SOLICITUD';
export const USER_GET_EJECUCION = 'USER_GET_EJECUCION';
export const USER_GET_RESPONSE = 'USER_GET_RESPONSE'; 