export const TICKET_FIND_SOLICITUD  = 'TICKET_FIND_SOLICITUD';
export const TICKET_FIND_EJECUCION = 'TICKET_FIND_EJECUCION';
export const TICKET_FIND_RESPONSE = 'TICKET_FIND_RESPONSE'; 

export const TICKET_DELETE_SOLICITUD  = 'TICKET_DELETE_SOLICITUD';
export const TICKET_DELETE_EJECUCION = 'TICKET_DELETE_EJECUCION';
export const TICKET_DELETE_RESPONSE = 'TICKET_DELETE_RESPONSE'; 


export const TICKET_CREATE_SOLICITUD  = 'TICKET_CREATE_SOLICITUD';
export const TICKET_CREATE_EJECUCION = 'TICKET_CREATE_EJECUCION';
export const TICKET_CREATE_RESPONSE = 'TICKET_CREATE_RESPONSE'; 


export const TICKET_EDIT_SOLICITUD  = 'TICKET_EDIT_SOLICITUD';
export const TICKET_EDIT_EJECUCION = 'TICKET_EDIT_EJECUCION';
export const TICKET_EDIT_RESPONSE = 'TICKET_EDIT_RESPONSE'; 
export const TICKET_EDIT_VOID = 'TICKET_EDIT_VOID'; 

export const TICKET_UPDATE_SOLICITUD  = 'TICKET_UPDATE_SOLICITUD';
export const TICKET_UPDATE_EJECUCION = 'TICKET_UPDATE_EJECUCION';
export const TICKET_UPDATE_RESPONSE = 'TICKET_UPDATE_RESPONSE'; 
export const TICKET_UPDATE_VOID = 'TICKET_UPDATE_VOID'; 