export const USER_LOGIN_SOLICITUD  = 'USER_LOGIN_SOLICITUD';
export const USER_LOGIN_EJECUCION = 'USER_LOGIN_EJECUCION';
export const USER_LOGIN_RESPONSE = 'USER_LOGIN_RESPONSE'; 


export const AUTH_LOGOUT = 'AUTH_LOGOUT';